### ISSUE TITLE
Updateeffect does not work in version 0.3.0

### ISSUE THREAD

**Issue by WU1208** [wlanjie/trinity#108]
Updateeffect does not work in version 0.3.0,it just adds special effects to the whole video, but there is no time limit.Can you help me？

**Comment by khalilurrehman28** [comment]
On UpdateEffect its crash and didn't provide any crash log.Please provide any solution

**Comment by wlanjie** [comment]
using 0.3.1 fix this bug.

**Comment by khalilurrehman28** [comment]
Whenever i click on effect i get this error even on 0.3.1 update

Build fingerprint: 'Xiaomi/kenzo/kenzo:6.0.1/MMB29M/V10.2.1.0.MHOMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 27096, tid: 27152, name: Thread-1008  >>> com.testapp.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    r0 dc19605c  r1 00000016  r2 ab79acb8  r3 00000000
    r4 ab1477c4  r5 ab891230  r6 ab1477c0  r7 f39a37e8
    r8 00000438  r9 ab4d6148  sl ab4d6158  fp 00000004
    ip ab247ff8  sp f39a3798  lr dbf1e15f  pc dbf1e16e  cpsr 60010030

backtrace:
    #00 pc 000e816e  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity21FaceMakeupV2SubEffect11OnDrawFrameEPNS_13FaceDetectionENSt6__ndk14listIPNS_9SubEffectENS3_9allocatorIS6_EEEEiiiiiiy+173)
    #01 pc 000db40b  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity6Effect11OnDrawFrameEjiiiiy+146)
    #02 pc 000d8df1  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity12ImageProcess9OnProcessEjxiiii+122)
    #03 pc 000927e5  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity12CameraRecord4DrawEv+488)
    #04 pc 00093b19  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity12CameraRecord11RenderFrameEv+16)
    #05 pc 00095fa7  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity7Message7ExecuteEv+30)
    #06 pc 0009572b  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity7Handler14ProcessMessageEv+74)
    #07 pc 00095611  /data/app/com.testapp.app-1/lib/arm/libtrinity.so (_ZN7trinity7Handler18MessageQueueThreadEPv+4)
    #08 pc 0004185b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
    #09 pc 000192a5  /system/lib/libc.so (__start_thread+6)a
