### ISSUE TITLE
When I call TrinityVideoEditor.destroy, a crash occurs, in 0.3.0

### ISSUE THREAD

**Issue by WU1208** [wlanjie/trinity#109]
When I call TrinityVideoEditor.destroy, a crash occurs
[trinity_20201008.xlog.log](https://github.com/wlanjie/trinity/files/5363200/trinity_20201008.xlog.log)

**Comment by badcodercpp** [comment]
Provide crash information as well, log don't have any crash and device information.

**Comment by wlanjie** [comment]
Please refer to #95 for submitting problems, no information can not be solved

**Comment by WU1208** [comment]
@badcodercpp @wlanjie That's all 
![20201014172449](https://user-images.githubusercontent.com/13074367/95970334-68929780-0e42-11eb-97be-63aee559f7ba.png)

**Comment by wlanjie** [comment]
The information is incorrect, reference #95

**Comment by wlanjie** [comment]
![image](https://user-images.githubusercontent.com/4112636/95979392-25d6bc80-0e4e-11eb-813d-adff1a723396.png)

This is right

**Comment by WU1208** [comment]
@wlanjie @badcodercpp 
![20201015101142](https://user-images.githubusercontent.com/13074367/96069327-8ad2f680-0ed0-11eb-96f9-e1fea95e0d37.png)

**Comment by wlanjie** [comment]
Do not use 0.3.0 in the demo, the demo is not updated, and it does not match the new version library

**Comment by WU1208** [comment]
@wlanjie Can you tell me what caused the demo problem? If I don't know why, I think I will still make this mistake. please

**Comment by wlanjie** [comment]
0.3.0 has undergone a lot of refactoring in editing and playback, which is not applicable to the current demo

**Comment by WU1208** [comment]
@wlanjie I'm really sorry. If I want to solve this problem, what should I do? Can you give me an idea? I have nothing to refer to, please

**Comment by WU1208** [comment]
@wlanjie Now only surfaceview is used, only browsing is used, but it is still crash. Is there any other way to browse?

**Comment by wlanjie** [comment]
What about your crash information, you have no information, how can I judge it, just rely on your one sentence?

**Comment by wlanjie** [comment]
Before you ask a question, please refer to #95, follow the standard to ask questions, otherwise I will not answer

**Comment by WU1208** [comment]
I know,crash information is the same as the picture above, but I didn't make it clear. I created a new page to test,just call destroy
![202010153](https://user-images.githubusercontent.com/13074367/96102185-cbe6fd00-0f08-11eb-9a4b-57da7cdf1ee7.png)
![20201015](https://user-images.githubusercontent.com/13074367/96101007-9261c200-0f07-11eb-9798-cea2da68b189.png)
![202010152](https://user-images.githubusercontent.com/13074367/96101024-968ddf80-0f07-11eb-85ee-131382175a80.png)

**Comment by wlanjie** [comment]
Check these few lines of log in logcat to take a look
![image](https://user-images.githubusercontent.com/4112636/96103176-f4232b80-0f09-11eb-9938-56b7ea176959.png)

**Comment by WU1208** [comment]
@wlanjie before crash All
![202010156](https://user-images.githubusercontent.com/13074367/96108095-c93bd600-0f0f-11eb-8158-c875e4b18add.png)
![202010157](https://user-images.githubusercontent.com/13074367/96108136-d35dd480-0f0f-11eb-9820-c53ec6eb599b.png)
![202010158](https://user-images.githubusercontent.com/13074367/96108159-d8bb1f00-0f0f-11eb-851d-6e2931ecfa46.png)
![202010159](https://user-images.githubusercontent.com/13074367/96108173-dc4ea600-0f0f-11eb-8847-4f5f24db975f.png)

**Comment by wlanjie** [comment]
0.3.2 version fix this bug.
