### ISSUE TITLE
Can be pushed h264 to live stream

### ISSUE THREAD

**Issue by truongnguyenptit** [wlanjie/trinity#115]
Now I try using this library to live stream. Could you give me some advice?

**Comment by badcodercpp** [comment]
@truongnguyenptit if you want to send clips to h264 then first get clip using getClipAtIndex, change media codec to h264 or 265 then send to rtmp server, use FFMPEG for this, something like bellow - 
ffmpeg -re -f lavfi -i mediaClipSource -c:v libx264 -b:v 1600k -preset ultrafast -b 900k -c:a libfdk_aac -b:a 128k -s 1920×1080 -x264opts keyint=50 -g 25 -pix_fmt yuv420p -f flv “rtmp://p.ep246802.i.akamaientrypoint.net/EntryPoint flashver=FMLE/3.020(compatible;20FMSc/1.0) live=true pubUser=username pubPasswd=password playpath=dclive_1_1@246802

**Comment by wlanjie** [comment]
change mp4_muxer to rtmp push feature

**Comment by wlanjie** [comment]
you need build rtmp library, add cmake build

**Comment by truongnguyenptit** [comment]
Thank you @wlanjie , @badcodercpp for your feedback.

I custom Camera1 and I tried to encode from the SurfaceView (TrinityPreviewView). I pushed data to live stream server success. But the viewer can not see any filter applied to the face (only see the face). So could you show me, which method contain byte array has a filter applied?

**Comment by wlanjie** [comment]
You need to use the h264 encoded by camera_record.cc to push the stream, not the preview in the preview. The preview stream is the original camera stream and has no effect.

**Comment by truongnguyenptit** [comment]
Thank you for your response @wlanjie 
I read camera_record.cc and I see it return ByteArray in this method drainEncoderFromNative. Right?

**Comment by wlanjie** [comment]
![image](https://user-images.githubusercontent.com/4112636/97770283-d5a96b00-1b6c-11eb-8e1c-eebdc376ff65.png)

Here the texture is sent to the encoder for encoding

**Comment by truongnguyenptit** [comment]
Thank you so much. I try my best

**Comment by truongnguyenptit** [comment]
Hi @wlanjie 
I follow 
```if (encoding_ && nullptr != encoder_) {
        encoder_->Encode(static_cast<uint64_t>((getCurrentTime() - encode_time_) * speed_),
                texture_id);
    }```
in camera_record.cc
I found you wrote callback from c++ to kotin 
`drainEncoderFromNative`
in ```int MediaEncodeAdapter::DrainEncodeData() {``` (file media_encode_adapter)

Continue I tried parse sps and pps from ByteArray

`private fun drainEncoderFromNative(data: ByteArray): Int {` in file TrinityRecord.kt

my code decode sps and pps from buffer
```public Pair<ByteBuffer, ByteBuffer> decodeSpsPpsFromBuffer(ByteBuffer outputBuffer, int length) {
    byte[] mSPS = null, mPPS = null;
    byte[] csd = new byte[length];
    outputBuffer.get(csd, 0, length);
    int i = 0;
    int spsIndex = -1;
    int ppsIndex = -1;
    while (i < length - 4) {
      if (csd[i] == 0 && csd[i + 1] == 0 && csd[i + 2] == 0 && csd[i + 3] == 1) {
        if (spsIndex == -1) {
          spsIndex = i;
        } else {
          ppsIndex = i;
          break;
        }
      }
      i++;
    }
    if (spsIndex != -1 && ppsIndex != -1) {
      mSPS = new byte[ppsIndex];
      System.arraycopy(csd, spsIndex, mSPS, 0, ppsIndex);
      mPPS = new byte[length - ppsIndex];
      System.arraycopy(csd, ppsIndex, mPPS, 0, length - ppsIndex);
    }
    if (mSPS != null && mPPS != null) {
      return new Pair<>(ByteBuffer.wrap(mSPS), ByteBuffer.wrap(mPPS));
    }
    return null;
  }```

My purpose gets byteArray (h264 from your library) and then use flv push to stream.

I hope your help. Many thanks.

**Comment by wlanjie** [comment]
Why do you want to call back? Can you just use rtmp to push it up in C++?
![image](https://user-images.githubusercontent.com/4112636/97825362-61500280-1cf9-11eb-8322-0f338d0c486d.png)

Writing local files is finally written here

**Comment by truongnguyenptit** [comment]
@wlanjie I don't know C++, I code rtmp by kotlin. it works well with the camera.  I tried to dive deep into your code.  Thank you for sharing.

**Comment by HrsonaliIndia** [comment]
Hi @wlanjie ,
Hope You are doing well !

We are the startup company of India developing short vedio creating app for Android & IOS so trying to integrate trinity vedio editing SDK in our application but facing bugs during integration so can u plz help us in resolving these issue.
So please kindly revert with your positive response at hrsonali@theuwo.com
Hoping for ur positive reply
