### ISSUE TITLE
Camera Recording is not working

### ISSUE THREAD

**Issue by burhansaykalvala** [wlanjie/trinity#13]
Video Not Previewing
         
                 I just downloaded the source code, After recording from the camera, the preview is not showing in Editor Activity.

**Comment by wlanjie** [comment]
Please describe the following steps, or send out the log at the address of /sdcard/trinity/trinity_20200206.xlog

**Comment by burhansaykalvala** [comment]
Hello, Check the log file.
[trinity_20200210.zip](https://github.com/wlanjie/trinity/files/4180461/trinity_20200210.zip)

**Comment by wlanjie** [comment]
The file is saved to /storage/emulated/0/Android/data/com.trinity.sample/cache/VID_20200210_161656.mp4 You can see it locally
