### ISSUE TITLE
ERROR: Failed to resolve: trinity

### ISSUE THREAD

**Issue by shubhwicked** [wlanjie/trinity#16]
while providing a path in Gradle, it is getting failed.

ERROR: Failed to resolve: trinity

**Comment by shubhwicked** [comment]
implementation 'com.github.wlanjie:trinity:0.2.6'

**Comment by wlanjie** [comment]
I uploaded again, you try again

**Comment by shubhwicked** [comment]
ok sure

**Comment by shubhwicked** [comment]
Same problem persist!

**Comment by wlanjie** [comment]
I can download it with me, Please check the network and project build.gradle jcenter() Whether the method is added

**Comment by shubhwicked** [comment]
ok.
