### ISSUE TITLE
Red track freeze on video edit and effects do not work

### ISSUE THREAD

**Issue by jonataslaw** [wlanjie/trinity#18]
First, I want to thank you for this library. There is no such open source library on Github as incredible as this one, and it is very promising.
I realized that in the video editing tab, it is not possible to drag the video to the beginning to apply effects in the desired area, and that if you record the video with the device's camera, many effects are not applied, the red band of effects is stopped and the effects application is inoperative, and there is no way to make a minimal edit.

Are you using ffmpeg for what in that lib? Depending on what you are doing, ffmpeg may be using a codec not available for video, this is just a guess, as I haven't had time to check your code yet.
Or the size of the video on my device because it is larger than the lib can render, as I said, these are just my guesses.
And congratulations once again for maintaining such an incredible job.

**Comment by wlanjie** [comment]
First of all, due to limited energy, the function of dragging the application effect has not been realized. At present, the ffmpeg decoder only supports the mp4 format

**Comment by wlanjie** [comment]
Can wait for subsequent version updates

**Comment by jonataslaw** [comment]
Thanks for your answer. I will wait, and I understand that it is a lot of work to create a lib as the only contributor. You can now close this issue.

**Comment by wlanjie** [comment]
okay, I look forward to your continued submission of issue and pull request.
