### ISSUE TITLE
支持java工程吗？

### ISSUE THREAD

**Issue by manbuxingkong** [wlanjie/trinity#20]
支持java工程吗？

**Comment by wlanjie** [comment]
不支持,涉及到很多Android相关的,比如Camera, 麦克风的采集, View的显示, OpenSL声音播放等

**Comment by manbuxingkong** [comment]
我可能表述的意思有歧义，我的意思是java语言写的Android工程可以引用吗？因为我看您这个开源库是kotlin编写的

**Comment by wlanjie** [comment]
可以的,java和kotlin可以通用

**Comment by manbuxingkong** [comment]
ok，谢谢大佬
