### ISSUE TITLE
Using the library in a Java Project

### ISSUE THREAD

**Issue by utk994** [wlanjie/trinity#22]
Is it possible to call this library in a java project ?
If yes, could you provide a short sample of how to do so ?

I have tried calling it normally as follows 

```
mContentView = (TrinityPreviewView) findViewById(R.id.preview);
mRecord = new TrinityRecord(this,mContentView);
mRecord.setOnRenderListener(this);
mRecord.setOnRecordingListener(this);
mRecord.setCameraCallback(this);
mRecord.startPreview(PreviewResolution.RESOLUTION_1920x1080);
```
However I get the following error 

`No implementation found for long com.trinity.record.TrinityRecord.create() (tried Java_com_trinity_record_TrinityRecord_create and Java_com_trinity_record_TrinityRecord_create__)`

**Comment by wlanjie** [comment]
Please Call       
      System.loadLibrary("trinity")
      System.loadLibrary("c++_shared")
      System.loadLibrary("marsxlog")

**Comment by utk994** [comment]
Thanks that worked

**Comment by kishanverma26** [comment]
> System.loadLibrary("trinity")

i am getting crash on this line
it says 

> /system/lib64, /system/product/lib64]]] couldn't find "libtrinity.so"

**Comment by wlanjie** [comment]
> > System.loadLibrary("trinity")
> 
> i am getting crash on this line
> it says
> 
> > /system/lib64, /system/product/lib64]]] couldn't find "libtrinity.so"


What architecture is your phone, only supports armeabi-v7a and arm64-v8a

**Comment by amyy11** [comment]
Hi Any plan to add support to other Architecture (x86) in coming days. it will be really great if u add support for it also

**Comment by wlanjie** [comment]
no,No plans to support x86 at the moment

**Comment by vaibhav-droid** [comment]
I am using arm64, pixel 2
