### ISSUE TITLE
能不能在录视频的时候添加个时间水印

### ISSUE THREAD

**Issue by akingyin1987** [wlanjie/trinity#26]

**Comment by wlanjie** [comment]
可以做,但是现在没时间

**Comment by dev-fancyluo** [comment]
加1，希望能加个添加时间水印

**Comment by wlanjie** [comment]
@dev-fancyluo 在下个版本会加上,现在正在做seek预览的功能,一个人开发可能进度没有那么快

**Comment by wlanjie** [comment]
参考 app中录制添加的spaceBear, 可以添加一个动态水印, 以下为更新水印设置方法
 // 贴纸显示的宽, 0~1.0
// 参数解释: spaceBear为effectName, 是在解析effect数组中的type为intoSticker中的name
 // stickerWidth 为固定的, 如果想更新显示区域则必须为stickerWidth
 mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerWidth", 0.23f)
 // 贴纸距离屏幕左边的距离, 左上角为原点, 0~1.0
mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerX", 0.13f)
// 贴纸距离屏幕上边的距离, 左上角为原点, 0~1.0
mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerY", 0.13f)
// 贴纸旋转的角度, 顺时针 0~360度
mRecord.updateActionParam(
                mIdentifyId,
                "spaceBear",
                "stickerRotate",
                0f
              )
删除的方法还是以前的,没做改动

**Comment by wlanjie** [comment]
参考 app中录制添加的spaceBear, 可以添加一个动态水印, 以下为更新水印设置方法
/** 贴纸显示的宽, 0-1.0 */
/** 参数解释: spaceBear为effectName, 是在解析effect数组中的type为intoSticker中的name */
/** stickerWidth 为固定的, 如果想更新显示区域则必须为stickerWidth */
mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerWidth", 0.23f)
/** 贴纸距离屏幕左边的距离, 左上角为原点, 0-1.0 */
mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerX", 0.13f)
/** 贴纸距离屏幕上边的距离, 左上角为原点, 0-1.0 */
mRecord.updateActionParam(mIdentifyId, "spaceBear", "stickerY", 0.13f)
/** 贴纸旋转的角度, 顺时针 0360度 */
mRecord.updateActionParam(
mIdentifyId,
"spaceBear",
"stickerRotate",
0f
)

如果只想添加一个静态水印,可以将spaceBear.json中的frames保留一个即可

删除的方法还是以前的,没做改动

**Comment by wlanjie** [comment]
或者使用 implementation 'com.github.wlanjie:trinity:0.2.9' maven版本
