### ISSUE TITLE
Geeting issue in effects while using images and video from Gallery 

### ISSUE THREAD

**Issue by kishanverma26** [wlanjie/trinity#29]
**Below you can see images**

**This image you can see showing on full screen if i use first efffect that is heart effect**

![Screenshot_20200609-114004](https://user-images.githubusercontent.com/20377886/84112485-7d02f580-aa46-11ea-981c-6b8fe63e41a5.jpg)

**in this you can see black screen gap on top and right side please have a look and let me know if i can help you in fixing this issue**

![Screenshot_20200609-114012](https://user-images.githubusercontent.com/20377886/84112488-7f654f80-aa46-11ea-98d1-0952c8f710fc.jpg)

**Comment by wlanjie** [comment]
I have fixed it, you will see the effect of the repair next time you submit, thank you

**Comment by kishanverma26** [comment]
> I have fixed it, you will see the effect of the repair next time you submit, thank you

Your work is really amazing and effect that you have added i would like to learn.
You have used OpenGl for effects right?

**Comment by wlanjie** [comment]
yes, I have used OpenGL for effect display, I don’t know what you want to learn

**Comment by kishanverma26** [comment]
i think this issue is solved

**Comment by qadirsuh** [comment]
Hello.

I am facing issue on this screen too
![image](https://user-images.githubusercontent.com/14326497/90344230-1d6e2b00-e031-11ea-9793-d6c52bf021e4.png)

effects red Indicator not showing at my side
