### ISSUE TITLE
Vertical video became horizontal video  

### ISSUE THREAD

**Issue by kishanverma26** [wlanjie/trinity#32]
When i select video from media (Gallery) after selecting in editor Vertical video became horizontal video  any idea how to fix this

**Comment by wlanjie** [comment]
This problem may need to get the rotate information of the video, and then do the rotation of the vertex coordinates or the rotation of the matrix

**Comment by kishanverma26** [comment]
ok i am on it .
you can also check 
Test cases are:
Make a vertical video from your device normally 
and then pic it from gallery as we usually do  in trinity app

**Comment by wlanjie** [comment]
I found this problem in the test and will fix it later

**Comment by kishanverma26** [comment]
> I found this problem in the test and will fix it later

okk thanks i am also looking for solution i will suggest you if i can fix this

**Comment by kishanverma26** [comment]
> or the rot

its already as vertically
if i play video is gallery it is playing verticals
but in editor it is showing horizontally

**Comment by wlanjie** [comment]
yes, gallery video Contains a 90-degree header file

**Comment by wlanjie** [comment]
fix v0.2.9.1 version, using implementation 'com.github.wlanjie:trinity:0.2.9.1'

**Comment by kishanverma26** [comment]
ok let me check

**Comment by kishanverma26** [comment]
> fix v0.2.9.1 version, using implementation 'com.github.wlanjie:trinity:0.2.9.1'

Great it is fixed now thanks man 
i am closing this

**Comment by vaibhav-droid** [comment]
@kishanverma26 are you using this lib in your android project ? while i am adding this lib to my project and trying to sign the app am getting error on load library..can you please help me out with this
