### ISSUE TITLE
About migrating the SDK project

### ISSUE THREAD

**Issue by kevinMintnick** [wlanjie/trinity#40]
What should I do if I need to migrate this SDK project to the project I am developing now?

Do you just need to import dependencies or do you need to copy the entire project?

**Comment by wlanjie** [comment]
implementation 'com.github.wlanjie:trinity:0.2.9.1'

**Comment by kevinMintnick** [comment]
I tried to add implementation ' com.github.wlanjie:trinity:0.2.9.1 ' in gradle config
However, the debugging runtime needs to wait for a long time at download core-0.0.5.aar every time.
I try to use VPN and other tools, but I still can't download it quickly.

**Comment by kevinMintnick** [comment]
![Snipaste_2020-07-11_14-26-51](https://user-images.githubusercontent.com/53930316/87218147-aa62fc00-c382-11ea-974f-0cf884a95e8b.png)

**Comment by wlanjie** [comment]
core-0.0.5.aar is not a sdk dependency

**Comment by kevinMintnick** [comment]
Thank you very much. Do I need to copy the layout file in the demo project?

**Comment by wlanjie** [comment]
no, layout own design
