### ISSUE TITLE
App crashing randomly

### ISSUE THREAD

**Issue by phoenixvk** [wlanjie/trinity#43]
I admit your hard-work.  So far the best open source code to work on binary media.
But app is crashing at many places.

I am using pixel 3.

**Comment by wlanjie** [comment]
yes, I have not undergone large-scale testing

**Comment by amyy11** [comment]
Hi @wlanjie 

Am too Facing same issue on my pixel 2 xl.. any update or resolution to it.. if fix provided it will be really great.

Thanks in Advance

**Comment by amyy11** [comment]
if possible request you to provide quick fix..

Thanks

**Comment by phoenixvk** [comment]
Closing this issue New Lib working Great.

**Comment by rocky8roy** [comment]
@phoenixvk hey possible to provide working sample code?
