### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 14888 (Thread-11121), pid 14328

### ISSUE THREAD

**Issue by sau05** [wlanjie/trinity#54]
App is crashing while scrolling video inside special effect section under EditorActivity

**Comment by Vishrtr** [comment]
Waiting for this but to get fixed. It is the most important part of sdk

**Comment by wlanjie** [comment]
using implementation 'com.github.wlanjie:trinity:0.3.0' video editor call prepare before playing
