### ISSUE TITLE
Text  / Subtitle added is not added into video after export

### ISSUE THREAD

**Issue by rootkick** [wlanjie/trinity#56]

**Comment by rootkick** [comment]
@wlanjie

**Comment by wlanjie** [comment]
This function is not implemented

**Comment by shashankjha1994** [comment]
@wlanjie we have added some features in this for text and stickers support. Happy to share.

**Comment by wlanjie** [comment]
Very good, please submit a pr

**Comment by SuryaChundawat** [comment]
@shashankjha1994  @wlanjie  can you please help me out in this.

**Comment by wlanjie** [comment]
not implementation, do it yourself

**Comment by arbaaj98** [comment]
> @wlanjie we have added some features in this for text and stickers support. Happy to share.

 Please help me I  also want  to add text  on my video
