### ISSUE TITLE
update

### ISSUE THREAD

**Issue by amyy11** [wlanjie/trinity#57]
hi

when new update can be expected with fixes

Random crash issues & other minor issue etc

**Comment by wlanjie** [comment]
I'm not sure, I haven't had time to update recently

**Comment by amyy11** [comment]
hi When update is scheduled. Thanks in Advance.. really you doing great job

**Comment by wlanjie** [comment]
Not sure yet, it's still under development, I only have spare time to do development, not so fast

**Comment by amyy11** [comment]
Hi @wlanjie , till when good news (Update) is expected. thanks for all support and great work.

**Comment by wlanjie** [comment]
Please wait, the stable version is expected to be released at the end of September or early October. There is no guarantee at this time, but I will release it as soon as possible

**Comment by amyy11** [comment]
Hi @wlanjie how are you, any update when new stable version will be available ..Thanks

**Comment by wlanjie** [comment]
using implementation 'com.github.wlanjie:trinity:0.3.0' video editor call prepare before playing

**Comment by amyy11** [comment]
hi @wlanjie  when new updated apk and files will be available ... still in this nice code/library crash issue exist in spite of updating library to 0.3.2. i know you are very busy and hardly find time still request  you to kindly do the needful to make it crash free.  Thanks for all help and support
