### ISSUE TITLE
setBackgroundMusic not working

### ISSUE THREAD

**Issue by monusk111** [wlanjie/trinity#58]
mRecord.setBackgroundMusic does not work

**Comment by hgaharwar** [comment]
I can help you with that mailme at @harshits008@gmail.com

**Comment by monusk111** [comment]
I have emailed you please respond..

**Comment by hgaharwar** [comment]
Can you please send me the class file where you are using audio player

**Comment by AlankritaShah** [comment]
@monusk111 could you find the solution for this?

**Comment by wlanjie** [comment]
using implementation 'com.github.wlanjie:trinity:0.3.0' video editor call prepare before playing
