### ISSUE TITLE
App dose not install

### ISSUE THREAD

**Issue by falguni0314** [wlanjie/trinity#59]
Hi, I have added the library but while installing the app getting below error, kindly help

**More than one file was found with OS independent path 'lib/armeabi-v7a/libc++_shared.so'.**

**Comment by hgaharwar** [comment]
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'

    }

include this in your gradle file above compiled sdk version in android tags

**Comment by falguni0314** [comment]
Thanks a lot...it worked.
