### ISSUE TITLE
mute original audio when add new music to recorded video

### ISSUE THREAD

**Issue by jondesoza523** [wlanjie/trinity#62]
Please, Give a perfect solution for that.

**Comment by wlanjie** [comment]
You just set all the audio data buffers to 0

**Comment by ahsandeveloper1601** [comment]
i am also facing the same issue can you elaborate this issue more in detail

**Comment by jondesoza523** [comment]
Thanks for response ,
Please explain something about that detail.

**Comment by ahsandeveloper1601** [comment]
First Excellent work that you have done.
whenever i add the sound in the video which i picked from the gallery both
the sound which is original sound of video and the sound which i added play
at the same time i want to mute the original sound

**Comment by wlanjie** [comment]
When you are playing, you only need to set the data sent to opensl to 0 using memset. When exporting, you need to set the data sent to the encoder to 0. Is this clear enough?

**Comment by ahsandeveloper1601** [comment]
sorry i did not get your point can you tell me which player your are using to play the video

**Comment by ahsandeveloper1601** [comment]
i am java android developer i dont have enough knowledge about kotlin

**Comment by ahsandeveloper1601** [comment]
and also in recording sreen when i need music in the background i work perfectly but when i move to the next edit screen the sound did not merge with the video

**Comment by jondesoza523** [comment]
> When you are playing, you only need to set the data sent to opensl to 0 using memset. When exporting, you need to set the data sent to the encoder to 0. Is this clear enough?

yes thank you

**Comment by ahsandeveloper1601** [comment]
@jondesoza523 can you send the code if you understand what he is saying

**Comment by wlanjie** [comment]
If you still can’t understand this, then I can’t do anything.

**Comment by ahsandeveloper1601** [comment]
can you tell me in which class i need to do this

**Comment by wlanjie** [comment]
player.cc AudioCallback method

**Comment by ahsandeveloper1601** [comment]
int Player::AudioCallback(uint8_t** buffer, int* buffer_size, void* context) {
    auto* player = reinterpret_cast<Player*>(context);
    int ret = player->GetAudioFrame();
    *buffer = player->audio_buffer_;
    *buffer_size = player->audio_buffer_size_;
    return ret;
}

**Comment by wlanjie** [comment]
yes, *buffer is return to opensl play, you need using memset clear this buffer to 0

**Comment by ahsandeveloper1601** [comment]
int Player::AudioCallback(uint8_t** buffer, int* buffer_size, void* context) {
    auto* player = reinterpret_cast<Player*>(context);
    int ret = player->GetAudioFrame();
    *buffer = player->audio_buffer_;
    *buffer_size = player->audio_buffer_size_;
    memset(&(buffer_size), 0, sizeof(buffer_size));
    return ret;
}
is this the right ???

**Comment by wlanjie** [comment]
Brother, find someone to help you, have you ever written C++

**Comment by ahsandeveloper1601** [comment]
no i work in java

**Comment by ahsandeveloper1601** [comment]
please help me out with this

**Comment by monusk111** [comment]
can anyone help me with setMusic doesn't work in EditorActivity as yours is working please :(

**Comment by ahsandeveloper1601** [comment]
fun setMusic(path: String) {
    val jsonObject = JSONObject()
    jsonObject.put("path", path)
   // mediaController.setVolumeTo(0,0)
    if (mMusicId != -1) {
      Log.d("dsdsddsds", "mMusicId after : $mMusicId")
      mVideoEditor.updateMusic(jsonObject.toString(), mMusicId)

    } else {

     mVideoEditor.addMusic(jsonObject.toString())
      Log.d("dsdsddsds", "12345888 : $mMusicId")
    }
    closeBottomSheet()
  }

use this code actually

**Comment by ahsandeveloper1601** [comment]
@wlanjie  memset(audio_buffer_, 0, sizeof(audio_buffer_size_)); is this the right way to do this please help me

**Comment by monusk111** [comment]
> fun setMusic(path: String) {
> val jsonObject = JSONObject()
> jsonObject.put("path", path)
> // mediaController.setVolumeTo(0,0)
> if (mMusicId != -1) {
> Log.d("dsdsddsds", "mMusicId after : $mMusicId")
> mVideoEditor.updateMusic(jsonObject.toString(), mMusicId)
> 
> ```
> } else {
> 
>  mVideoEditor.addMusic(jsonObject.toString())
>   Log.d("dsdsddsds", "12345888 : $mMusicId")
> }
> closeBottomSheet()
> ```
> 
> }
> 
> use this code actually

sadly ,this is not working

**Comment by ahsandeveloper1601** [comment]
its working for me uninstall and then try it again

**Comment by monusk111** [comment]
> fun setMusic(path: String) {
> val jsonObject = JSONObject()
> jsonObject.put("path", path)
> // mediaController.setVolumeTo(0,0)
> if (mMusicId != -1) {
> Log.d("dsdsddsds", "mMusicId after : $mMusicId")
> mVideoEditor.updateMusic(jsonObject.toString(), mMusicId)
> 
> ```
> } else {
> 
>  mVideoEditor.addMusic(jsonObject.toString())
>   Log.d("dsdsddsds", "12345888 : $mMusicId")
> }
> closeBottomSheet()
> ```
> 
> }
> 
> use this code actually

This code is working but in preview the sound isn't audible

**Comment by ahsandeveloper1601** [comment]
it is

**Comment by rocky8roy** [comment]
> it is

it works but not always..even when selecting music on record screen, the music sets sometime and sometime nothing plays.
but for example if music gets selected successfully on record screen then it will play on editor activity too.
i have also logged the set music thing and it sometimes sets the music and sometimes dont set it.

**Comment by rocky8roy** [comment]
> fun setMusic(path: String) {
> val jsonObject = JSONObject()
> jsonObject.put("path", path)
> // mediaController.setVolumeTo(0,0)
> if (mMusicId != -1) {
> Log.d("dsdsddsds", "mMusicId after : $mMusicId")
> mVideoEditor.updateMusic(jsonObject.toString(), mMusicId)
> 
> ```
> } else {
> 
>  mVideoEditor.addMusic(jsonObject.toString())
>   Log.d("dsdsddsds", "12345888 : $mMusicId")
> }
> closeBottomSheet()
> ```
> 
> }
> 
> use this code actually

are there any changes in the original code.. i dont see any change in above and original code provided other than Log thing

**Comment by rocky8roy** [comment]
> Please, Give a perfect solution for that.

Are you able to set the audio everytime when you select add audio on record activity?
because when i select music on record activity it sometimes fails to select the music.
Its a random behaviour so can really say when it will setmusic or it will not set music.
are you facing the same problem or just mute audio isssue?

**Comment by wlanjie** [comment]
memset(audio_buffer_, 0, audio_buffer_size_);

**Comment by ahsandeveloper1601** [comment]
i have use this line in the method and this error comes up  
Invalid use of member 'audio_buffer_' in static member function 
when i make the method non-static then new error appears and same for when i make audio buffer static

**Comment by wlanjie** [comment]
You can fix the problem and submit a pull request to merge, I don't have much time for development

**Comment by wlanjie** [comment]
0.3.0 version
Use the volume and mute of MediaClip to set the volume and mute function, and then call the updateClip of VideoEditor
