### ISSUE TITLE
Help Needed: any way to stop recording audio from camera when background music is selected at kotlin end ??

### ISSUE THREAD

**Issue by badcodercpp** [wlanjie/trinity#71]

**Comment by shashankjha1994** [comment]
We did a way around on this using ffmpeg. Happy to share the solution. Incase you need help, just drop me a mail on shashank@webloomsolutions.com

**Comment by badcodercpp** [comment]
> We did a way around on this using ffmpeg. Happy to share the solution. Incase you need help, just drop me a mail on [shashank@webloomsolutions.com](mailto:shashank@webloomsolutions.com)

dropped you mail from badcodercpp@gmail.com , please check once .

**Comment by ahsandeveloper1601** [comment]
i have done by setting audioBitrate to 0

**Comment by badcodercpp** [comment]
@zeropoint7877 yeah i got but it will reset audioBitrate to 0 always and will not record camera audio right ? can it e done conditionally somehow ?

**Comment by wlanjie** [comment]
A version will be sent to jcenter recently
