### ISSUE TITLE
List of all Issues in this wonderful Library  (eg Memory issue and other issues) 

### ISSUE THREAD

**Issue by rocky8roy** [wlanjie/trinity#74]
App crashes at so many places randomly for eg:
1) when editing the video.. in timeline recyclerview just drag forward and backwards fast and it crashes
2) click on export and it will crash randomly on many phones.. i guess its again memory issue
3) Sound/music add doesn't get selected most of the time at recording screen.

Export video process is very nicely done as it process the effects and other stuff very fast ( Note : wherever it works ) 

Anyone who has solved the the above issues kindly reply here or connect with me on rocky8roy@gmail.com. Will be happy to help eachother.

**Comment by wlanjie** [comment]
A version will be sent to jcenter recently

**Comment by rocky8roy** [comment]
> A version will be sent to jcenter recently

i can see latest version is v0.2.9.1 everywhere.
When new version is sent to jcenter?????

**Comment by tauqeer-crewlogix** [comment]
@rocky8roy have you found the latest version?

**Comment by wlanjie** [comment]
The latest version will be submitted in a few days, and the document will be updated after submission

**Comment by tauqeer-crewlogix** [comment]
@wlanjie Guys you are doing some really good stuff. I am also using this library. i am waiting for the next version. Can you tell me when will be the next version released?

**Comment by wlanjie** [comment]
Not sure, it may be within 10 days

**Comment by wlanjie** [comment]
I will submit aar and documents to jcenter, but currently the code will not be pushed to master

**Comment by tauqeer-crewlogix** [comment]
ok, then I am waiting for the next version.

**Comment by OneBusyBrain** [comment]
By when will the new version be submitted ?

**Comment by Vishrtr** [comment]
Any update on the bug fixes ?

**Comment by wlanjie** [comment]
i want to know when the new update will be available
