### ISSUE TITLE
Clarification needed : Remote path for background music supported ? 

### ISSUE THREAD

**Issue by badcodercpp** [wlanjie/trinity#75]

**Comment by wlanjie** [comment]
No, you need to download it locally and set it to sdk

**Comment by badcodercpp** [comment]
@wlanjie sorry but i didn't get the statement 'set it to sdk' , after downloading do i need to move somewhere ?? what is the path or url for sdk ??? will it not accept file:// url ??

**Comment by wlanjie** [comment]
/sdcard/a.mp3

**Comment by badcodercpp** [comment]
@wlanjie  thank you so much that worked, you are best man :) , one last query on this , what if device don't have mounted sdcard then will it work or not ?

**Comment by wlanjie** [comment]
If the file cannot be opened, the result is not 0, no music effect
