### ISSUE TITLE
Build is not Successful after adding as a Library in my application

### ISSUE THREAD

**Issue by tauqeer-crewlogix** [wlanjie/trinity#77]
Error while executing process C:\Users\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe -C E:\Projects\TrinityTest\library\.cxx\cmake\debug\arm64-v8a trinity}
ninja: Entering directory `E:\Projects\TrinityTest\library\.cxx\cmake\debug\arm64-v8a'

ninja: error: 'E:/Projects/TrinityTest/extra/ffmpeg/arm64-v8a/lib/libswresample.a', needed by 'E:/Projects/TrinityTest/library/build/intermediates/cmake/debug/obj/arm64-v8a/libtrinity.so', missing and no known rule to make it

**Comment by tauqeer-crewlogix** [comment]
I am adding it as a Module in my project but it gives me this error. Any Idea?

**Comment by tauqeer-crewlogix** [comment]
Fixed. Adding Extra folder to my project.

**Comment by vaibhav-droid** [comment]
its arm64 . i am using pixel 2 but getting error
