### ISSUE TITLE
clarification needed: Is Raw FFMPEG is accessible anyhow in this library? will be helpful to write ffmpeg filter or more enhanced plugin like subtitle support in current one, if ffmpeg is accessible. 

### ISSUE THREAD

**Issue by badcodercpp** [wlanjie/trinity#79]

**Comment by wlanjie** [comment]
ffmpeg uses version 3.4, you can go to the official website to download and compile by yourself, but it is not recommended to use ffmpeg filters to do too much operation, it is recommended to use opengl to operate
