### ISSUE TITLE
No music playback in Editor

### ISSUE THREAD

**Issue by tatirajurishabh** [wlanjie/trinity#81]
Below is the code block being used by me to add music to Video Editor instance:
```
if (musicId == -1) {
    musicId = editor?.addMusic(config.toString()) ?: -1
} else {
    editor?.updateMusic(config.toString(), musicId)
}
```
The config is:
```
{
    "path":"/data/user/0/blog.rishabh.trinity/cache/musicfile.mp3",
    "startTime":0,
    "endTime":239102
}

```
Music is not played back in the editor. However, once the video is exported, music shows up in the exported final video.

**Comment by shashankjha1994** [comment]
+1 
I've the same issues.

**Comment by wlanjie** [comment]
Please use mars to parse the log file and submit

**Comment by wlanjie** [comment]
using implementation 'com.github.wlanjie:trinity:0.3.0' video editor call prepare before playing
