### ISSUE TITLE
Getting error on applaunch

### ISSUE THREAD

**Issue by vaibhav-droid** [wlanjie/trinity#85]
trying to load libs but getting following crash in application class

JNI DETECTED ERROR IN APPLICATION: JNI RegisterNatives called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.trinity.record.TrinityRecord" on path: DexPathList[[zip file "/data/app/packagename-zrA4TygNqudIuL_hAw-pwA==/base.apk"],nativeLibraryDirectories=[/data/app/packagename-zrA4TygNqudIuL_hAw-pwA==/lib/arm64, /data/app/packagename-zrA4TygNqudIuL_hAw-pwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

**Comment by wlanjie** [comment]
see #22

**Comment by vaibhav-droid** [comment]
@wlanjie I am getting this issue only in release build. Its working fine in debug build.
