### ISSUE TITLE
NoSuchMethodError in TrinityRecord

### ISSUE THREAD

**Issue by vaibhav-droid** [wlanjie/trinity#87]
getting this issue in application class

JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lcom/trinity/record/TrinityRecord;.updateTextureMatrix(J[F)V"
2020-09-09 09:53:29.416 9332-9332/A/: runtime.cc:638]   at void <clinit>() (:26)
2020-09-09 09:53:29.416 9332-9332/ A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9332 , pid 9332

**Comment by wlanjie** [comment]
Demo or own app?

**Comment by vaibhav-droid** [comment]
own app

**Comment by vaibhav-droid** [comment]
got the solution... minifyenabled was true in my gradle file. setting it to false worked (Y)

**Comment by vaibhav-droid** [comment]
@wlanjie but can you please share some proguard rules to work with minfity enabled as it is directly affecting build size and app security

**Comment by wlanjie** [comment]
SDK all filters, don't be confused

**Comment by vaibhav-droid** [comment]
@wlanjie can you please explain in detail.. getting error if minify enabled true..

**Comment by wlanjie** [comment]
Because all java and kotlin will involve jni methods, so all can not be confused
