### ISSUE TITLE
帧率过低,希望能给出不同设备的性能测试数据

### ISSUE THREAD

**Issue by liduanwei** [wlanjie/trinity#9]

**Comment by wlanjie** [comment]
你指的帧率是预览还是录制出来的视频?

**Comment by liduanwei** [comment]
> 你指的帧率是预览还是录制出来的视频?

录制出来的视频的帧率非常低, 只有10帧左右

**Comment by wlanjie** [comment]
在低端机上不建议使用软编码,因为软编码需要从opengl中读取当前帧的内容,这里会比较耗时,只有当硬编码不可用时,才开启软编码
